---
abstract: 'Parse xml to simple tree'
author:
  - 'Mons Anderson <mons@cpan.org>'
build_requires:
  Test::More: 0
  XML::Parser: 0
  ex::lib: 0
distribution_type: module
generated_by: 'Module::Install version 0.71'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: XML-Parser-Style-EasyTree
no_index:
  directory:
    - inc
    - t
requires:
  Scalar::Util: 0
version: 0.01
